export const arrayListPlayerFifa = [
    {
        name : "gino",
        surname:"Pino",
        nickname:"THEBEST",
        src:require("../assets/alien.png"),
        nation:"Italia",
        role:"Giocatore",
        linkTwitter:"https://twitter.com",
        linkYoutube:"https://youtube.com",
        linkTwitch:"",
        age:19,
        linkInstagram:"",
        isActive:false,
    },
    {
        name : "fra",
        surname:"omosex",
        nickname:"GAY",
        nation:"Italia",
        role:"Giocatore",
        src:require("../assets/alien.png"),
        linkTwitter:"https://twitter.com",
        linkYoutube:"https://youtube.com",
        linkTwitch:"https://twitch.com",
        age:19,
        linkInstagram:"https://instagram.com",
        isActive:false,
    }
]